version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped
    # Para entorno de desarrollo, descomentar estas líneas:
    # volumes:
    #   - ./src:/app/src
    #   - ./public:/app/public
    # command: npm run dev
    # environment:
    #   - NODE_ENV=development
    #   - VITE_API_URL=http://api:8000
